<?php
    require_once('db.php');
    require_once('session.php');
    require_once('config.php');
    require_once('upload.php');
    require_once('level_require.php');
    require_once('auth.php');
    require_once('functions.php');
?>